push_indications:
  description: Pushes indications with specified values for a meter
  fields:
    entity_id:
      description: 'ID of a meter or account to push indications for'
      example: 'sensor.mes_meter_1234567'
    indications:
      description: 'List of values (from 1 to 3) for tariffs: [T1, T2, T3]'
      example: '[123, 456, 789]'
    ignore_period:
      description: 'Ignore period boundaries'
      example: 'false'

calculate_indications:
  description: Подсчитать начисления по передаваемым показаниям
  fields:
    entity_id:
      description: 'Идентификатор объекта счётчика, для которого подсчитывать показания'
      example: 'sensor.mes_meter_1234567'
    indications:
      description: 'List of values (from 1 to 3) for tariffs: [T1, T2, T3]'
      example: '[123, 456, 789]'
    ignore_period:
      description: 'Ignore period boundaries'
      example: 'false'