push_indications:
  description: 'Передать показания в личный кабинет'
  fields:
    entity_id:
      description: 'Идентификатор объекта целевого счётчика (не совместимо с `meter_code`)'
      example: 'sensor.mes_meter_1234567'
    meter_code:
      description: 'Номер целевого счётчика (не совместимо с `entity_id`)'
      example: '1234567'
    indications:
      description: 'Список показаний (от 1 до 3) для тарифов: [T1, T2, T3]'
      example: '[123, 456, 789]'
    incremental:
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      example: 'false'
    ignore_period:
      description: 'Игнорировать ограничения по периоду'
      example: 'false'
    notification:
      description: 'Показывать уведомление при успешной передаче'
      example: 'true'

calculate_indications:
  description: 'Подсчитать начисления по передаваемым показаниям'
  fields:
    entity_id:
      description: 'Идентификатор объекта целевого счётчика (не совместимо с `meter_code`)'
      example: 'sensor.mes_meter_1234567'
    meter_code:
      description: 'Номер целевого счётчика (не совместимо с `entity_id`)'
      example: '1234567'
    indications:
      description: 'Список показаний (от 1 до 3) для тарифов: [T1, T2, T3]'
      example: '[123, 456, 789]'
    incremental:
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      example: 'false'
    ignore_period:
      description: 'Игнорировать ограничения по периоду'
      example: 'false'
    notification:
      description: 'Показывать уведомление при успешном подсчёте'
      example: 'true'